labproject/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace labproject.Models
{
    public class Student
    {
        public String Name { get; set; }
        public String RegistrationNumber { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

labproject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace labproject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

labproject/Controllers/StudentController.cs
using labproject.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace labproject.Controllers
{
    public class StudentController : ApiController
    {
        [HttpPost]
        public bool AddStudent(Student obj)
        {
            try
            {
                StreamWriter writer = new StreamWriter("G:/Test.txt", true);
                writer.WriteLine(obj.Name + "," + obj.RegistrationNumber + "," + obj.DateOfBirth);
                writer.Flush();
                writer.Close();

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
        [HttpGet]
        public List<Student> AllStudents()
        {
            List<Student> data = new List<Student>();

            StreamReader reader = new StreamReader("G:/Test.txt");

            String line = reader.ReadLine();

            while (line != null)
            {
                String[] arr = line.Split(',');
                Student s = new Student();
                s.Name = arr[0];
                s.RegistrationNumber = arr[1];
                s.DateOfBirth = DateTime.Parse(arr[2]);
                data.Add(s);

                line = reader.ReadLine();
            }
            return data;
        }
    }
}

labproject/Controllers/StudentViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace labproject.Controllers
{
    public class StudentViewController : Controller
    {
        // GET: StudentView
        public ActionResult StudentList()
        {
            return View();
        }

        public ActionResult AddStudentPage()
        {
            return View();
        }
    }
}

labproject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

labproject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

labproject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

labproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Add New Page", "AddStudentPage", "StudentView")</li>
                    <li>@Html.ActionLink("List of All Students", "StudentList", "StudentView")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

labproject/Views/StudentView/AddStudentPage.cshtml
<style>
    .main {
        margin: auto;
        width: 340px;
        margin-top: 100px;
        background-color: #edebeb;
        text-align: center;
    }

        .main label {
            display: inline-block;
            text-align: right;
            font-family: Arial;
            color: black;
            font-size: 24px;
        }

        .main input {
            display: inline-block;
            text-align: center;
            font-family: Arial;
            color: black;
            font-size: 24px;
        }

    h1 {
        font-family: Arial;
        color: teal;
        font-size: 68px;
    }

    button {
        font-family: Arial;
        background-color: teal;
        color: white;
        font-size: 28px;
        margin-bottom: 20px;
    }

    body {
        background-image: url("https://source.unsplash.com/1366x768/?nature,water");
    }
</style>


<div class="main">
    <h1>Student</h1>
    <br>
    <label for="stdName">Name</label>
    <input type="text" name="Name" id="stdName">
    <br>
    <label for="regNo">Registration Number</label>
    <input type="text" name="RegNo" id="regNo" style="margin-top: 15px;">
    <br>
    <label for="dob">Date of Birth</label>
    <input type="date" name="DOB" id="dob" style="margin-top: 15px;">
    <br>
    <button type="submit" style="margin-top: 15px;" onclick="save()">OK</button>
</div>
@section scripts{
    <script>
        function save() {
            var n = document.getElementById("stdName").value;
            var reg = document.getElementById("regNo").value;
            var date = document.getElementById("dob").value;


            var obj = {
                Name: n,
                RegistrationNumber: reg,
                DateOfBirth: date
            };

            var data = JSON.stringify(obj);
            console.log(data);

    


            $.ajax({
                url: "http://localhost:56514/api/Student/AddStudent",
                type: 'POST',
                data: JSON.stringify(obj),
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    alert(data);
                },
                error: function (data) {
                }
            });

            //	window.location = "";

        }
    </script>

}

labproject/Views/StudentView/StudentList.cshtml
<div id="myTable"></div>

@section scripts{
<script>

    $.get( "http://localhost:56514/api/Student/AllStudents")
			.done(function( data ) {
				console.log(data);
				var stg= "";

				stg = "<table>";
				var i;
				for (i = 0; i < data.length; i++) {
								stg = stg+ "<tr><td>"+ data[i].Name + "</td>"
									+ "<td>"+ data[i].RegistrationNumber + "</td>"
									+ "<td>"+ data[i].DateOfBirth + "</td></tr>";
				}

				stg = stg+ "</table>";
				console.log(stg);
				$("#myTable").html(stg);

		});
</script>

    }